server:
  port: 8888
  servlet:
    context-path: /demo1
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
    cache: false
 # mvc:
  #  view:
 #     prefix:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.243.138.3:3306/vue2test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: vue
    password: vue1234
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  type-aliases-package: com.testspringboot.lottery.dao
  mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    mapUnderscoreToCamelCase: true
    localCacheScope: statement
    jdbcTypeForNull: null